# Generated by Django 4.2.11 on 2024-03-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
